"use client";
import "./globals.css";
import { coolvetica, timesNewRoman } from "@/public/fonts";
import DesktopMenu from "@/components/layout/DesktopMenu";
import { usePathname } from "next/navigation";

// Note: metadata can't be used in client components, so we'll handle this differently
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // Map different pages to different hand images
  const getBackgroundImage = (path: string) => {
    switch (path) {
      case "/":
        return "/images/hands/handsOne.png";
      case "/cast-and-crew":
        return "/images/hands/handsTwo.png";
      case "/press":
        return "/images/hands/handsThree.png";
      case "/reading-list":
        return "/images/hands/handsFour.png";
      default:
        return "/images/hands/handsOne.png";
    }
  };

  return (
    <html lang="en">
      <head>
        <title>Doomers</title>
        <meta
          name="description"
          content="In humanity's last act, who plays god?"
        />
      </head>
      <body
        className={`${timesNewRoman.variable} ${coolvetica.variable} antialiased flex relative transition-all duration-1000 ease-in-out`}
        style={{
          backgroundImage: `url('${getBackgroundImage(pathname)}')`,
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
        }}
      >
        <DesktopMenu />
        {children}
      </body>
    </html>
  );
}
