import "./globals.css";
import { coolvetica, helveticaNeue, timesNewRoman } from "@/public/fonts";

// Note: metadata can't be used in client components, so we'll handle this differently
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Doomers</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <meta
          name="description"
          content="In humanity's last act, who plays god?"
        />
      </head>
      <body
        className={`${timesNewRoman.variable} ${coolvetica.variable} ${helveticaNeue.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
