import "./globals.css";
import { coolvetica, timesNewRoman } from "@/public/fonts";

// Note: metadata can't be used in client components, so we'll handle this differently
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Doomers</title>
        <meta
          name="description"
          content="In humanity's last act, who plays god?"
        />
      </head>
      <body
        className={`${timesNewRoman.variable} ${coolvetica.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
